#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 30 16:47:04 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytrader3ee6'
    mvnCommands = '--version'
    test='false'
}