#!groovy

// Generated by IBM TransformationAdvisor
// Tue Apr 30 17:50:16 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytrader3ee6'
    mvnCommands = '--version'
    test='false'
}